export {default as Navbar} from './Navbar'
export {default as Slider} from './Slider'
export {default as Products} from './Products'
export {default as Product} from './Product'
export {default as Footer} from './Footer'